version: '3.8'

services:
  # MongoDB for development
  mongodb:
    image: mongo:6.0
    container_name: mern-blog-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mern-blog-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - mern-dev-network

  # Backend Server (Development)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: mern-blog-server-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/mern-blog-dev
      JWT_SECRET: dev-jwt-secret-key
      JWT_EXPIRE: 7d
      CLIENT_URL: http://localhost:3000
    ports:
      - "5000:5000"
      - "9229:9229" # Debug port
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - mern-dev-network
    command: npm run dev

  # Frontend Client (Development)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: mern-blog-client-dev
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - mern-dev-network
    command: npm run dev

volumes:
  mongodb_dev_data:
    driver: local

networks:
  mern-dev-network:
    driver: bridge
